#Workflow name

name: CI/CD Pipeline

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main

jobs:


  #Modificaciones Fer
  deploy:
    name: Deploy to AWS ECR
    runs-on: ubuntu-latest


    steps:
      # Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v2


      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          ls ../
          docker build -t arquisoft-lab2 -f ../Dockerfile .

      # Login a AWS ECR y subir la imagen
      - name: Login to AWS ECR and push image
        id: deploy-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Tag and push Docker image to AWS ECR
        run: |
          docker tag arquisoft-lab2:latest public.ecr.aws/e6r1j8j8/arquisoft-lab2:latest
          docker push public.ecr.aws/e6r1j8j8/arquisoft-lab2:latest

